import 'package:flutter/material.dart';
import 'package:flutterapp/praneshapp/generatedlogowidget21/generated/GeneratedLogo_appsWidget.dart';

/* Frame Logo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogoWidget21 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 200.0,
        height: 200.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(1.0000001192092864, -0.9999999630672374),
            end: Alignment(-0.9583332445989892, 0.9999999854111006),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 251, 179, 193),
              Color.fromARGB(255, 88, 124, 244)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 200.0,
                child: GeneratedLogo_appsWidget(),
              )
            ]),
      ),
    ));
  }
}
