import 'package:flutter/material.dart';
import 'package:flutterapp/praneshapp/generatedloginwidget/generated/GeneratedInputFormWidget3.dart';
import 'package:flutterapp/praneshapp/generatedloginwidget/generated/GeneratedSecondaryButtonWidget1.dart';
import 'package:flutterapp/praneshapp/generatedloginwidget/generated/GeneratedPrimaryButtonWidget1.dart';
import 'package:flutterapp/praneshapp/generatedloginwidget/generated/GeneratedInputFormWidget4.dart';
import 'package:flutterapp/praneshapp/generatedloginwidget/generated/GeneratedTitleWidget83.dart';
import 'package:flutterapp/praneshapp/generatedloginwidget/generated/GeneratedLinkButtonWidget.dart';
import 'package:flutterapp/praneshapp/generatedloginwidget/generated/GeneratedOptionInfoWidget1.dart';
import 'package:flutterapp/praneshapp/generatedloginwidget/generated/GeneratedDescWidget2.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 254.0,
                height: 50.0,
                child: GeneratedDescWidget2(),
              ),
              Positioned(
                left: 15.99999713897705,
                top: 182.99996948242188,
                right: null,
                bottom: null,
                width: 328.0,
                height: 52.500030517578125,
                child: GeneratedInputFormWidget3(),
              ),
              Positioned(
                left: 16.0,
                top: 387.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 44.0,
                child: GeneratedPrimaryButtonWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 44.0,
                child: GeneratedSecondaryButtonWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 15.0,
                child: GeneratedLinkButtonWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 53.000030517578125,
                child: GeneratedInputFormWidget4(),
              ),
              Positioned(
                left: 96.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 17.0,
                child: GeneratedOptionInfoWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 39.0,
                child: GeneratedTitleWidget83(),
              )
            ]),
      ),
    ));
  }
}
